version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
  - dependency-name: psr/container
    versions:
    - 2.0.0
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
