language: php
php:
    - 7.1
install:
    - composer install --prefer-source --no-interaction
script:
    - composer dump-autoload
    - ./vendor/bin/phpunit -c phpunit.xml
    - ./vendor/bin/phpcs -p ./src --report=summary --standard=./ruleset.xml
notifications:
    on_success: never
    on_failure: always
git:
    depth: 1
after_success:
    - bash <(curl -s https://codecov.io/bash)
